VIEW_MONITORING = 1;
VIEW_CONFIGURATION = 2;
VIEW_DIAGRAMS = 3;
VIEW_ALARMS = 4;
VIEW_ENVIRONMENT = 5;

SYSTEM_TASK = "Q_SYS";

COLOR_QINOUS_LIGHT_GREY = "#EEF1F2";
COLOR_ARROW_GREEN = "#9BC33D";
COLOR_ARROW_GREY = "#D1D7D8";

/// Group constants
TYPE_SYSTEM = -1;
TYPE_PV = 1;
TYPE_CONSUMER = 2;
TYPE_GRID = 3;
TYPE_BATTERY = 4;
TYPE_DIESEL = 5;
TYPE_RAWMETER = 6;

TYPE_PV_GROUP = 101;
TYPE_CONSUMER_GROUP = 102;
TYPE_BATTERY_GROUP = 104;
TYPE_DIESEL_GROUP = 105;

TYPE_SAMSUNG_RACK = 201;
