// Navigation
VIEW_MONITORING = 1;
VIEW_CONFIGURATION = 2;
VIEW_DIAGRAMS = 3;
VIEW_ALARMS = 4;
VIEW_ENVIRONMENT = 5;
VIEW_CONTROL = 6;

SYSTEM_TASK = "Q_SYS";
COLOR_QINOUS_GREEN = "#008C25";
COLOR_QINOUS_BLUE = "#00A7E0";
COLOR_QINOUS_YELLOW = "#E3CD00";
COLOR_ACTION = "#F44336";
COLOR_QINOUS_LIGHT_GREY = "#EEF1F2";
COLOR_ARROW_GREEN = "#9BC33D";
COLOR_ARROW_GREY = "#D1D7D8";

/// Group constants
TYPE_SYSTEM = -1;
TYPE_PV = 1;
TYPE_CONSUMER = 2;
TYPE_GRID = 3;
TYPE_BATTERY = 4;
TYPE_DIESEL = 5;
TYPE_RAWMETER = 6;

TYPE_PV_GROUP = 101;
TYPE_CONSUMER_GROUP = 102;
TYPE_BATTERY_GROUP = 104;
TYPE_DIESEL_GROUP = 105;

TYPE_BATTERY_STRING = 201

TYPE_SAMSUNG_RACK = 1201;


TYPE_CLIMATE = 301;

// Control View
CONTROL_BLOCKED = 1;
CONTROL_GUI = 2;
CONTROL_QINOUS = 3;
CONTROL_MODBUS = 4;
CONTROL_IEC_104 = 5;

// Tables
fontSize = 16;
fontcolumn = 13;

// User Rights
VIEW_PARAMETERS = "USER.View All Parameters";
EDIT_PARAMETERS = "USER.Edit All Parameters";
OPERATION_PARAMETERS = "USER.Operation Parameters";
VIEW_CONTROLS = "USER.View Controls";
APPLY_CONTROLS = "USER.Apply Controls";

LocalTimeSystemTimeDiff = 0;
BrowserTimeSytemTimeDiff = 0;



